# Generated by Django 5.1.8 on 2025-04-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_chat_id', models.BigIntegerField(unique=True, verbose_name='Student Chat ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('teacher_course_name', models.CharField(max_length=50, verbose_name="Teacher's Course Name")),
                ('teacher_name', models.CharField(max_length=100, verbose_name='Teacher Name')),
            ],
            options={
                'verbose_name': 'Student Info',
                'verbose_name_plural': 'Students Info',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.question', verbose_name='Related Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.studentinfo', verbose_name='Answered By')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answer',
                'ordering': ['-created_at'],
            },
        ),
    ]
